theme: jekyll-theme-minimal

title: Interesting things
description: What I found, and how I learned them.
url: https://katonalala.github.io/
social_media_list:
  linkedin: Lajos Katona
  github: katonalala
